### ISSUE TITLE
Improve robot tags control panel field

### ISSUE THREAD

**Issue by fredvd** [collective/collective.behavior.seo#2]
When administrators add two blank lines in the SEO robots field in the control panel, it will block
editing/adding all content with the behavior activated because the vocabulary generation crashes on duplicate ID's

 ```
Module zope.schema._field, line 312, in bind
  Module Zope2.App.schema, line 33, in get
  Module collective.behavior.seo.vocabularies, line 21, in __call__
  Module zope.schema.vocabulary, line 79, in __init__
ValueError: term values must be unique: u''
```

**Comment by mauritsvanrees** [comment]
Fixed, will be in release 2.0.0.
